{% set name = "objsize" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/objsize-{{ version }}.tar.gz
  sha256: d66bbb2a4341803caba84894b5753f9b065ebe1cbf50fd186ae438dfc1ca4729

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61.0.0
  run:
    - python >={{ python_min }}

test:
  imports:
    - objsize
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/liran-funaro/objsize
  summary: Traversal over Python's objects subtree and calculate the total size of the subtree in bytes (deep size).
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
